import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How blio handles account, campaign, prospect, and provider data.",
};

export default function PrivacyPage() {
  return <article className="legal-page"><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p className="legal-updated">Last updated: September 21, 2026</p><p>This policy explains how blio handles information when you use the blio prospecting workspace.</p><h2>Information we handle</h2><p>We handle your email address and account details, campaign settings, target locations, lead workflow notes, and outreach drafts. We also process public business information discovered for your campaigns, including business names, addresses, ratings, websites, public contact paths, images, and source links.</p><h2>Service providers</h2><p>Supabase provides authentication and database infrastructure. Outscraper provides Google Maps business discovery when configured. OpenAI processes campaign context and collected business evidence to create opportunity scores and outreach drafts. Provider credentials are kept server-side.</p><h2>How information is used</h2><p>Information is used to operate your workspace, discover and enrich prospects, score opportunities, generate editable drafts, maintain your pipeline, and improve reliability. blio does not send outreach messages automatically.</p><h2>Storage and access</h2><p>Production workspace data is stored in Supabase with row-level access controls. Demo mode stores data locally in the application workspace. You should not place secrets, sensitive personal data, or confidential customer information into campaign prompts or private notes unless your organization has approved that use.</p><h2>Your choices</h2><p>You may stop using the service, remove campaigns, archive prospects, or request deletion through the workspace owner. Provider retention and processing may also be subject to the policies of Supabase, Outscraper, and OpenAI.</p><h2>Updates</h2><p>We may update this policy as the product or providers change. The updated date above will identify the current version.</p></article>;
}
