import Link from "next/link";
import { ArrowLeft, Archive, Check, MapPin, Sparkles } from "lucide-react";

import { archiveCampaignAction, updateCampaignAction } from "@/app/actions";
import { getCurrentUser } from "@/lib/auth";
import { getCampaign } from "@/lib/data";
import { FormSubmitButton } from "@/components/form-submit-button";

export default async function EditCampaignPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const user = await getCurrentUser();
  if (!user) return null;
  const campaign = await getCampaign(user.id, id);
  if (!campaign) return <div className="empty-state"><h3>Campaign not found</h3><Link href="/campaigns" className="button button-primary">Back to campaigns</Link></div>;
  return (
    <>
      <Link className="back-link" href={`/campaigns/${id}`}><ArrowLeft size={14} /> Back to campaign</Link>
      <div className="topbar"><div><p className="eyebrow">Campaign settings</p><h1>Refine your prospecting brief.</h1><p className="subtitle">Change the offer, market, radius, or qualification signals before the next run.</p></div></div>
      {query.error ? <div className="alert alert-error" style={{ maxWidth: 880 }}>{query.error}</div> : null}
      <form className="card form-card" action={updateCampaignAction}>
        <input type="hidden" name="id" value={id} />
        <section className="form-section"><div className="form-step"><span className="step-number">01</span><div><h3>Offer and campaign</h3><p>Keep the sales opportunity clear.</p></div></div><div className="form-grid"><div className="form-field full"><label className="label" htmlFor="offer">Service or solution</label><textarea className="textarea" id="offer" name="offer" rows={3} defaultValue={campaign.context.offer} required /></div><div className="form-field"><label className="label" htmlFor="name">Campaign name</label><input className="input" id="name" name="name" defaultValue={campaign.name} required /></div><div className="form-field"><label className="label" htmlFor="cta">Call to action</label><input className="input" id="cta" name="cta" defaultValue={campaign.context.cta} /></div></div></section>
        <section className="form-section"><div className="form-step"><span className="step-number">02</span><div><h3>Target market</h3><p>Location → business type → search radius.</p></div></div><div className="form-grid"><div className="form-field"><label className="label" htmlFor="category">Business type</label><input className="input" id="category" name="category" defaultValue={campaign.category} required /></div><div className="form-field"><label className="label" htmlFor="radiusKm">Search radius</label><select className="select" id="radiusKm" name="radiusKm" defaultValue={String(campaign.radiusKm ?? 10)}><option value="1">1 km</option><option value="5">5 km</option><option value="10">10 km</option><option value="15">15 km</option><option value="25">25 km</option><option value="50">50 km</option></select></div><div className="form-field"><label className="label" htmlFor="leadLimit">Approx. prospects</label><select className="select" id="leadLimit" name="leadLimit" defaultValue={String(campaign.leadLimit ?? 50)}><option value="10">About 10</option><option value="25">About 25</option><option value="50">About 50</option><option value="100">About 100</option><option value="200">About 200</option><option value="500">About 500</option></select></div><div className="form-field full"><label className="label" htmlFor="locations">Target location</label><div className="input-with-icon"><MapPin size={16} /><input className="input" id="locations" name="locations" defaultValue={campaign.locations.join(", ")} required /></div></div></div></section>
        <section className="form-section"><div className="form-step"><span className="step-number">03</span><div><h3>Opportunity context</h3><p>Optional details sharpen scoring and outreach.</p></div></div><div className="form-grid"><div className="form-field"><label className="label" htmlFor="targetCustomer">Ideal customer</label><textarea className="textarea" id="targetCustomer" name="targetCustomer" rows={3} defaultValue={campaign.context.targetCustomer} /></div><div className="form-field"><label className="label" htmlFor="painPoint">Likely problem</label><textarea className="textarea" id="painPoint" name="painPoint" rows={3} defaultValue={campaign.context.painPoint} /></div><div className="form-field full"><label className="label" htmlFor="valueProposition">What changes after they work with you?</label><textarea className="textarea" id="valueProposition" name="valueProposition" rows={2} defaultValue={campaign.context.valueProposition} /></div></div></section>
        <details className="form-details"><summary><Sparkles size={15} /> Advanced filters and outreach voice</summary><div className="form-grid" style={{ marginTop: 18 }}><div className="form-field"><label className="label" htmlFor="minRating">Minimum rating</label><select className="select" id="minRating" name="minRating" defaultValue={campaign.filters.minRating?.toString() ?? ""}><option value="">Any rating</option><option value="4">4.0+</option><option value="4.3">4.3+</option><option value="4.5">4.5+</option><option value="4.7">4.7+</option></select></div><div className="form-field"><label className="label" htmlFor="minReviews">Minimum reviews</label><select className="select" id="minReviews" name="minReviews" defaultValue={campaign.filters.minReviews?.toString() ?? ""}><option value="">Any volume</option><option value="10">10+</option><option value="25">25+</option><option value="50">50+</option><option value="100">100+</option></select></div><div className="form-field"><label className="label" htmlFor="tone">Tone</label><select className="select" id="tone" name="tone" defaultValue={campaign.context.tone}><option>Warm, direct, and helpful</option><option>Concise and professional</option><option>Casual and conversational</option><option>Insightful and consultative</option></select></div><div className="form-field full"><div className="checkbox-grid"><label className="check-card"><input type="checkbox" name="websiteRequired" defaultChecked={campaign.filters.websiteRequired} /> Website detected</label><label className="check-card"><input type="checkbox" name="whatsappRequired" defaultChecked={campaign.filters.whatsappRequired} /> WhatsApp available</label><label className="check-card"><input type="checkbox" name="socialRequired" defaultChecked={campaign.filters.socialRequired} /> Social profile found</label></div></div></div></details>
        <div className="actions" style={{ justifyContent: "flex-start", paddingTop: 22 }}><FormSubmitButton pendingLabel="Saving changes…"><Check /> Save changes</FormSubmitButton><Link href={`/campaigns/${id}`} className="button button-secondary">Cancel</Link></div>
      </form>
      <section className="card section-card" style={{ maxWidth: 880, marginTop: 18 }}><div className="section-heading"><div><h2>Archive campaign</h2><p>Remove it from active views while preserving its lead history.</p></div></div><form action={archiveCampaignAction}><input type="hidden" name="id" value={id} /><FormSubmitButton className="button button-danger" pendingLabel="Archiving…"><Archive /> Archive campaign</FormSubmitButton></form></section>
    </>
  );
}
