import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "Terms for using the QuickLeads AI prospecting and outreach workspace.",
};

const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL ?? "kumod353@gmail.com";

export default function TermsPage() {
  return <article className="legal-page"><p className="eyebrow">Legal</p><h1>Terms and Conditions</h1><p className="legal-updated">Last updated: September 22, 2026</p><p>By using QuickLeads, you agree to use the workspace responsibly and in accordance with applicable law and the terms of the providers you connect to it.</p><h2>What QuickLeads provides</h2><p>QuickLeads provides tools to define a target market, discover public business information, analyze prospect fit, create outreach drafts, and manage a sales pipeline. Results are assistive and may be incomplete, inaccurate, outdated, or affected by provider availability.</p><h2>Your responsibilities</h2><p>You are responsible for your campaigns, imported data, notes, messages, recipient selection, consent requirements, and compliance with applicable marketing, privacy, telecommunications, and platform rules. Verify important facts before contacting a prospect.</p><h2>AI and provider output</h2><p>AI-generated scores, highlights, and messages are suggestions, not guarantees. You must review and edit them before use. QuickLeads does not guarantee lead volume, accuracy, conversions, deliverability, or business outcomes.</p><h2>Acceptable use</h2><p>Do not use QuickLeads to harass, deceive, impersonate, unlawfully profile, scrape restricted data, bypass provider controls, or send unsolicited communication in violation of applicable rules. Do not submit secrets or highly sensitive information to campaign context.</p><h2>Third-party services</h2><p>Discovery, AI, authentication, hosting, and other integrations may have separate terms, pricing, quotas, and availability. You are responsible for maintaining the accounts and billing relationships you configure.</p><h2>Changes and availability</h2><p>Features may change as the product develops. We may suspend access for abuse, security concerns, provider restrictions, or legal requirements. These terms should be reviewed by qualified legal counsel before production use.</p><h2>Contact</h2><p>Questions about these terms can be sent to <a className="text-link" href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p></article>;
}
